spring:
    application:
        name: "Zara Store Demo"
    datasource:
        url: ${DB_URL:jdbc:h2:file:./data/demo}
        driverClassName: ${DB_DRIVER:org.h2.Driver}
        username: ${DB_USER:h2user}
        password: ${DB_PASS:h2password}
    jpa:
        database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
        hibernate:
            ddl-auto: none
    flyway:
        enabled: ${FLYWAY_ENABLED:true}
        baseline-on-migrate: true
        locations: classpath:db/migration
        url: ${DB_URL:jdbc:h2:file:./data/demo}
        user: ${DB_USER:h2user}
        password: ${DB_PASS:h2password}
