CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);
CREATE TABLE PRODUCT_VARIANT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    SIZE VARCHAR(20) NOT NULL,
    STOCK INT NOT NULL,
    UNITS_SOLD INT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
    UNIQUE (PRODUCT_ID, SIZE)
);