--- Products
INSERT INTO PRODUCT (ID, NAME)
VALUES (1, 'V-NECH BASIC SHIRT');
INSERT INTO PRODUCT (ID, NAME)
VALUES (2, 'CONTRASTING FABRIC T-SHIRT');
INSERT INTO PRODUCT (ID, NAME)
VALUES (3, 'RAISED PRINT T-SHIRT');
INSERT INTO PRODUCT (ID, NAME)
VALUES (4, 'PLEATED T-SHIRT');
INSERT INTO PRODUCT (ID, NAME)
VALUES (5, 'CONTRASTING LACE T-SHIRT');
INSERT INTO PRODUCT (ID, NAME)
VALUES (6, 'SLOGAN T-SHIRT');
--- Variants
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (1, 'SMALL', 4, 30);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (1, 'MEDIUM', 9, 30);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (1, 'LARGE', 0, 40);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (2, 'SMALL', 35, 10);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (2, 'MEDIUM', 9, 20);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (2, 'LARGE', 9, 20);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (3, 'SMALL', 20, 30);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (3, 'MEDIUM', 2, 30);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (3, 'LARGE', 20, 20);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (4, 'SMALL', 25, 1);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (4, 'MEDIUM', 30, 1);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (4, 'LARGE', 10, 1);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (5, 'SMALL', 0, 25);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (5, 'MEDIUM', 1, 25);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (5, 'LARGE', 0, 600);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (6, 'SMALL', 9, 5);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (6, 'MEDIUM', 2, 5);
INSERT INTO PRODUCT_VARIANT (PRODUCT_ID, SIZE, STOCK, UNITS_SOLD)
VALUES (6, 'LARGE', 5, 10);